export default [
  {
    name: 'Boss 直聘',
    url: 'https://www.zhipin.com/',
    schoolUrl: 'https://www.zhipin.com/school/?ka=tab_school_recruit_click',
    desc: '头号招聘平台',
  },
  {
    name: '智联招聘',
    url: 'https://www.zhaopin.com/',
    schoolUrl: 'https://xiaoyuan.zhaopin.com/',
    desc: '头号招聘平台',
  },
  {
    name: '智联招聘-高端人才',
    url: 'https://highpin.zhaopin.com/zhiwei/',
    schoolUrl: 'https://xiaoyuan.zhaopin.com/',
    desc: '头号招聘平台',
  },
  {
    name: '智联招聘-猎头',
    url: 'https://highpin.zhaopin.com/HunterList/HunterRankingList',
    schoolUrl: 'https://xiaoyuan.zhaopin.com/',
    desc: '头号招聘平台',
  },
  {
    name: '前程无忧',
    url: 'https://www.51job.com',
    schoolUrl: 'https://xy.51job.com/default-xs.php',
    desc: '头号招聘平台',
  },
  {
    name: '百度招聘',
    url: 'https://yiqifu.baidu.com/g/aqc/joblist',
    schoolUrl: '',
    desc: '百度旗下',
  },
  {
    name: '猎聘网',
    url: 'https://www.liepin.com/',
    schoolUrl: 'https://www.liepin.com/campus/?t=1',
    desc: '主打高端',
  },
  {
    name: '中国发展简报NGO',
    url: 'https://www.chinadevelopmentbrief.org.cn/',
    schoolUrl: '',
    desc: '北京益行公益信息交流服务中心',
  },
  {
    name: '人名日报招聘',
    url: 'https://hr.peopledaily.com.cn/Recruitment/notice/list.html?g=2',
    schoolUrl: 'https://hr.peopledaily.com.cn/Recruitment/notice/list.html?g=1',
    desc: '人名日报',
  },
  {
    name: '淘工作',
    url: 'https://www.alizhaopin.com/index.htm',
    schoolUrl: '',
    desc: '由浙江日报报业集团和阿里巴巴集团共同投资组建',
  },
  {
    name: '店长直聘',
    url: 'https://www.dianzhangzhipin.com/',
    schoolUrl: '',
    desc: 'Boss直聘旗下',
  },
  {
    name: '中智招聘网',
    url: 'https://www.ciiczhaopin.com/index',
    schoolUrl: 'https://www.ciiczhaopin.com/campus/index',
    desc: '中智集团有国务院管理，招聘网站【国家级】',
  },
  {
    name: '中华英才招聘网',
    url: 'https://www.chinahr.com/',
    schoolUrl: 'https://www.chinahr.com/campusRecruitment',
    desc: '北京五八信息技术有限公司旗下',
  },
  {
    name: '58同城',
    url: 'https://dl.58.com/job.shtml',
    desc: '北京五八信息技术有限公司旗下',
  },
  {
    name: '赶集直招',
    url: 'https://bj.ganji.com/',
    desc: '赶集网成立于2005年，是专业的分类信息网',
  },
  {
    name: '百姓网',
    url: 'https://beijing.baixing.com/gongzuo/',
    desc: '百姓网股份有限公司',
  },
  {
    name: '猪八戒网（找外包、找全职、找兼职）',
    url: 'https://www.zbj.com/',
    desc: '猪八戒股份有限公司',
  },
  {
    name: '597Z直聘网',
    url: 'https://www.597.com/changecity.html',
    desc: '厦门才盛人才服务有限公司',
  },
  {
    name: '大学生招聘网',
    url: 'https://www.zhaopinhui.net/',
    schoolUrl: 'https://www.zhaopinhui.net/',
    desc: '分类比较全，各地方招聘会',
  },
  {
    name: '拉勾网',
    url: 'https://www.lagou.com/',
    schoolUrl: 'https://xiaoyuan.lagou.com/',
    desc: '拉勾招聘是专业的互联网求职招聘网站',
  },
  {
    name: '牛客网',
    url: 'https://www.nowcoder.com/jobs/fulltime/center',
    schoolUrl: 'https://www.nowcoder.com/jobs/recommend/campus',
    desc: '互联网招聘',
  },
  {
    name: '新职业 - 教育部',
    url: 'https://www.ncss.cn/',
    schoolUrl: 'https://www.ncss.cn/',
    desc: '教育部学生服务与素质发展中心',
  },
  {
    name: '海投网（校招）',
    url: 'https://www.haitou.cc/',
    schoolUrl: 'https://www.haitou.cc/',
    desc: '武汉公司，国家社保基金领投',
  },
  {
    name: '应届生求职网',
    url: 'https://www.yingjiesheng.com/',
    desc: '前程无忧旗下校招',
  },
  {
    name: '实习僧（主实习）',
    url: 'https://resume.shixiseng.com/xiaozhao',
    schoolUrl: 'https://www.yingjiesheng.com/https://resume.shixiseng.com/xiaozhao',
    desc: '成都萌想科技有限责任公司',
  },
  {
    name: '211校招网',
    url: 'https://www.211zph.com/https://www.iguopin.com/',
    schoolUrl: 'https://www.211zph.com/jobfair/xyzph.dohttps://xiaoyuan.iguopin.com/',
    desc: '西安大秦人力资源有限公司网站',
  },
  {
    name: '国聘网（大型)',
    url: 'https://www.iguopin.com/',
    schoolUrl: 'https://xiaoyuan.iguopin.com/',
    desc: '国投人力资源服务有限公司',
  },
  {
    name: '中国公共招聘网',
    url: 'http://job.mohrss.gov.cn/',
    schoolUrl: 'http://job.mohrss.gov.cn/202008gx/index.jhtml',
    desc: '中华人民共和国人力资源和社会保障部',
  },
  {
    name: '就业在线',
    url: 'https://www.jobonline.cn/',
    schoolUrl: 'https://www.jobonline.cn/collegeGraduatesNew',
    desc: '平安养老保险股份有限公司旗下',
  },
  {
    name: '卫人就业网（卫生护士）',
    url: 'https://www.weirenjob.com/zph/',
    schoolUrl: 'https://www.weirenjob.com/zph/',
    desc: '北京卫人人才网络有限公司',
  },
  {
    name: '中国残疾人就业创业网络服务平台',
    url: 'https://www.cdpee.org.cn/',
    desc: '北京卫人人才网络科技有限公司中国残疾人联合会就业服务指导中心',
  },
  {
    name: '中国社会科学院',
    url: 'https://cass.gjzhaopin.cn/LPSC/LEAP/zgshkxy/html/index.html',
  },
  {
    name: '国有资产监督管理会',
    url: 'http://www.sasac.gov.cn/n2588035/n2588325/n2588350/index.html',
    desc: '国有资产监督管理会',
  },
  {
    name: '国家自然科学',
    url: 'https://www.nsfc.gov.cn/publish/portal0/tab476/',
    desc: '国家自然科学基金委员会',
  },
  {
    name: '军事人才网',
    url: 'http://81rc.81.cn/',
    desc: '解放军报社',
  },
  {
    name: '国家电网招聘',
    url: 'https://zhaopin.sgcc.com.cn/sgcchr/static/home.html',
    schoolUrl: 'https://zhaopin.sgcc.com.cn/sgcchr/static/home.html',
    desc: '国家电网有限公司',
  },
  {
    name: '中国水利人才',
    url: 'http://rencai.mwr.cn/zpks/zpgg/',
  },
  {
    name: '全国事业单位招聘（事业单位）',
    url: 'https://www.qgsydw.com/qgsydw/index.html',
    desc: '广州网才信息技术有限公司（广州人才集团有限公司控股）',
  },
  {
    name: '事业单位招聘',
    url: 'https://www.shiyebian.net/',
    desc: '山东轻云网络科技有限公司',
  },
  {
    name: '普通人才（制造业）',
    url: 'https://www.job5156.com/',
    desc: '广东智通人才连锁股份有限公司',
  },
  {
    name: '留学人才网',
    url: 'http://www.liuxuehr.com/',
  },
  {
    name: '高校毕业生精准招聘平台',
    url: 'https://xyzp.newjobs.com.cn/',
  },
  {
    name: '教育部人才服务网',
    url: 'https://iybzp.chsi.com.cn/home/index',
    schoolUrl: 'https://iybzp.chsi.com.cn/home/jobs?orgld=xkkizntxpmzszhcp&identity=1.',
  },
  {
    name: '高校人才网（海归、事业单位）',
    url: 'https://www.gaoxiaojob.com/',
    schoolUrl: 'https://zhaopin.sgcc.com.cn/sgcchr/static/home.html',
    desc: '广州高才信息科技有限公司',
  },
  {
    name: '公务员考试网',
    url: 'https://www.chinagwy.org/',
  },
  {
    name: '事业编招聘',
    url: 'http://www.yingyudengji.com/',
  },
  {
    name: '高层次人才',
    url: 'www.gccrcw.com',
  },
  {
    name: '卓博人才网',
    url: 'https://www.jobcn.com/',
    desc: '广州卓博信息科技有限公司',
  },
  {
    name: '数英网（创业、设计、运营）',
    url: 'https://www.digitaling.com/search/jobs',
    desc: '代盟企业管理咨询（上海）有限公司',
  },
  {
    name: '金融英才网云队友(远程工作）',
    url: 'https://www.bankhr.com/https://jx.duiyou360.com/',
    desc: '东绩网络科技（上海）有限公司',
  },
  {
    name: '建筑英才网（建筑）',
    url: 'https://www.buildhr.com/',
    schoolUrl: 'https://campus.buildhr.com/',
    desc: '英才网联(北京)咨询有限公司',
  },
  {
    name: '中国建筑人才（建筑）',
    url: 'http://www.buildjob.net/',
    schoolUrl: 'http://www.buildjob.net/school/index.jsp',
    desc: '深圳市万泉河科技股份有限公司',
  },
  {
    name: '最佳东方（旅游、餐饮、海外）',
    url: 'https://www.veryeast.cn/',
    desc: '杭州东方网升科技股份有限公司',
  },
  {
    name: '化工英才网',
    url: 'https://www.chenhr.com/',
    schoolUrl: 'https://campus.chenhr.com/',
    desc: '英才网联（北京）咨询有限公司',
  },
  {
    name: '中国卫生人才网',
    url: 'https://www.weirenjob.com/zph/',
    desc: '国家卫生健康委人才交流服务中心',
  },
  {
    name: '丁香人才网（药企）',
    url: 'https://www.jobmd.cn/',
    schoolUrl: 'https://xiaoyuan.jobmd.cn/',
    desc: '杭州联科美讯生物医药技术有限公司',
  },
  {
    name: '医药英才网',
    url: 'https://www.healthr.com/',
    schoolUrl: 'https://campus.healthr.com/',
  },
  {
    name: '医疗卫生人才网',
    url: 'https://www.job120.com/',
    desc: '杭州万行人力资源服务有限公司',
  },
  {
    name: '北极星招聘(电力、能源、工程)',
    url: 'https://hr.bjx.com.cn/',
    schoolUrl: 'https://xiaoyuan.bjx.com.cn/',
  },
  {
    name: '一览英才网',
    url: 'www.job1001.com',
    schoolUrl: 'https://yjs.job1001.com/',
  },
  {
    name: '外语人才网',
    url: 'www.jobeast.com',
    desc: '深圳市一览网络股份有限公司杭州万行人力资源服务有限公司',
  },
  {
    name: '招教网（教师招聘考试）',
    url: 'https://www.zhaojiao.net/',
    desc: '郑州如志教育图书科技文化有限公司',
  },
  {
    name: '教师招聘网（教师）',
    url: 'https://www.job910.com/',
    desc: '杭州万行人力资源服务有限公司',
  },
  {
    name: '南京教育局（教师）',
    url: 'https://edu.nanjing.gov.cn/bsfw/zpzk',
    desc: '南京教育局',
  },
  {
    name: '中南招聘网(深圳)',
    url: 'https://www.znhr.com/',
    schoolUrl: 'https://www.znhr.com/school',
    desc: '深圳市新路程职业介绍服务有限公司旗下',
  },
  {
    name: '今日招聘网站',
    url: 'www.jrzp.com/',
    schoolUrl: 'https://www.jrzp.com/xiaoyuanzhaopin/',
    desc: '杭州滨兴科技股份有限公司',
  },
  {
    name: '服装人才网',
    url: 'https://www.cfw.cn/',
    desc: '个人公司',
  },
  {
    name: '鱼泡招聘网（无计算机招聘）',
    url: 'https://www.yupao.com/a1/',
    schoolUrl: '成都鱼泡科技有限公司',
  },
  {
    name: '找工易招聘网',
    url: 'www.hunt007.com',
    schoolUrl: 'http://www.hunt007.com/xian-yingjiesheng.htm',
    desc: '广州昂鼎信息科技有限公司',
  },
  {
    name: '青岛人才网',
    url: 'https://rc.qingdao.gov.cn/zhaopin/',
    desc: '青岛市大数据发展管理局（青岛市电子政务管理办公室)',
  },
  {
    name: '百城招聘',
    url: 'https://www.bczp.cn/',
    schoolUrl: 'https://all.bczp.cn/School/Index.aspx',
    desc: '广州百城人才网络股份有限公司',
  },
  {
    name: '招聘会网（招聘会汇总）',
    url: 'https://www.zph.com.cn/',
    schoolUrl: 'https://www.zph.com.cn/xiaoyuan/',
  },
  {
    name: '研究生求职网（海内外硕士博士）',
    url: 'https://www.591yjs.cn/',
  },
  {
    name: '人才职业网',
    url: 'https://rencaijob.com/',
  },
  {
    name: '乐聘网',
    url: 'https://www.61hr.com/',
    desc: '上海谋事成数字科技（集团）有限公司',
  },
];
