export default [
  {
    province: '北京市',
    authorityUrl: 'https://rsj.beijing.gov.cn/xxgk/gkzp/',
    placeName: '北京国际人才',
    placeUrl: 'https://www.bjrcgz.gov.cn/',
  },
  {
    province: '天津市',
    authorityUrl: 'https://hrss.tj.gov.cn/ztzl/ztzl1/sydwgkzp/',
    placeName: '天津人才',
    placeUrl: 'http://www.tjrenliziyuan.com/',
  },
  {
    province: '天津市',
    authorityUrl: 'https://hrss.tj.gov.cn/ztzl/ztzl1/sydwgkzp/',
    placeName: '泰达人才',
    placeUrl: 'https://www.tedahr.com/',
  },
  {
    province: '上海市',
    authorityUrl: 'https://rsj.sh.gov.cn/tsydwgkzp_17406/index.html',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '重庆市',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '重庆人才-1',
    placeUrl: 'https://www.huibo.com/',
  },
  {
    province: '重庆市',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '重庆人才-2',
    placeUrl: 'https://www.cqrc.net/',
  },
  {
    province: '安徽省',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '心安人才',
    placeUrl: 'https://www.ahrcw.com/',
  },
  {
    province: '安徽省',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '安徽人才网-1',
    placeUrl: 'http://www.chinaahrc.com/',
  },
  {
    province: '安徽省',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '安徽人才网-2',
    placeUrl: 'https://www.goodjobs.cn/',
  },
  {
    province: '安徽省',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '安徽人公共招聘',
    placeUrl: 'https://www.ahggzp.gov.cn/ww/b/c/wwbc_result.html',
  },
  {
    province: '安徽省',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '新安人才网校园招聘',
    placeUrl: 'https://campus.goodjobs.cn/',
  },
  {
    province: '安徽省',
    authorityUrl: 'https://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html',
    placeName: '合肥招聘网',
    placeUrl: 'https://www.hfzp.cc/',
  },
  {
    province: '福建省',
    authorityUrl: 'https://rst.fujian.gov.cn/',
    placeName: '福建人才网',
    placeUrl: 'http://www.chinafjrc.com/',
  },
  {
    province: '福建省',
    authorityUrl: 'https://rst.fujian.gov.cn/',
    placeName: '厦门人才网',
    placeUrl: 'https://www.xmrc.com.cn/',
  },
  {
    province: '福建省',
    authorityUrl: 'https://rst.fujian.gov.cn/',
    placeName: '泉州人才网',
    placeUrl: 'https://www.qzrc.com/',
  },
  {
    province: '福建省',
    authorityUrl: 'https://rst.fujian.gov.cn/',
    placeName: '还下人才网',
    placeUrl: 'https://www.hxrc.cn/user/',
  },
  {
    province: '甘肃省',
    authorityUrl: 'https://www.gscn.com.cn/rst/',
    placeName: '甘肃人事',
    placeUrl: 'https://ks.rst.gansu.gov.cn/ncms/index.shtml',
  },
  {
    province: '甘肃省',
    authorityUrl: 'https://www.gscn.com.cn/rst/',
    placeName: '甘肃人才网',
    placeUrl: 'https://www.gszhaopin.com/content/jobs.html',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '广东省人才市场',
    placeUrl: 'https://www.gdrc.com/',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '广东国际人才',
    placeUrl: 'https://www.job001.cn/index',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '深圳人才网',
    placeUrl: 'https://www.szhr.com.cn/#/',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '百城招聘',
    placeUrl: 'https://all.bczp.cn/',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '南方人才网',
    placeUrl: 'https://www.job168.com/',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '花都人才网',
    placeUrl: 'https://www.job088.com/',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '番禺人才网',
    placeUrl: 'https://www.pyrc.com.cn/df/py/jobIndex.jsp?defaultPy=1',
  },
  {
    province: '广东省',
    authorityUrl: 'https://hrss.gd.gov.cn/zwgk/gsgg/index.html',
    placeName: '广东国际人才（校招）',
    placeUrl: 'https://www.job001.cn/branch/school/home',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
  {
    province: '',
    authorityUrl: '',
    placeName: '',
    placeUrl: '',
  },
];
